### PR TITLE
[HCFRO-182] Bump CF MSBuild tasks to CC v236

### PR DESCRIPTION
**Pull request by calinmiclaus**

### CODE REVIEW

**Comment by calinmiclaus** [comment]
verify this please

**Comment by calinmiclaus** [comment]
verify this please

**Comment by calinmiclaus** [comment]
verify this please

**Comment by calinmiclaus** [comment]
verify this please

**Comment by calinmiclaus** [comment]
verify this please

**Comment by calinmiclaus** [comment]
verify this please

**Comment by mihaibuzgau** [comment]
closing due to bad line endings

**Pull request closed without merging**
