### PR TITLE
Parse loggregator message timestamp as unix nano

### PR DESCRIPTION
**Pull request by stefanschneider**
Logging failed when pushing an app to cf + bosh-lite. This patch may fix the issue.

@carabasdaniel  @mihaibuzgau  can you please check this out?

### CODE REVIEW

**Comment by stefanschneider** [comment]
verify this please

**Comment by stefanschneider** [comment]
verify this please

**Comment by stefanschneider** [comment]
verify this please

**Comment by stefanschneider** [comment]
@carabasdaniel @mihaibuzgau can you please check this out? the build is also fixed :)

**Comment by carabasdaniel** [comment]
:+1:  looks good to me

**Comment by viovanov** [comment]
:+1:

**Pull request merged**
